Option to specify nonperiodic parts of the topographic PV gradients in `MultiLayerQG`
FourierFlows/GeophysicalFlows.jl pull request #313
Opened 2022-12-09 15:35 UTC by apaloczy

This closes #307 by adding options to specify a nonperiodic component of the topographic PV gradients (for example a planar slope) in the `MultiLayerQG` module. Also added one test.

The gradients of the nonperiodic part of the topographic PV are now specified separately via `etax_nonperiodic` and `etay_nonperiodic` in `MultiLayerQG.Problem`, and are added to the gradients of the periodic part of the topographic PV (calculated via FFTs).

2022-12-10 10:24 UTC, navidcy commented on src/multilayerqg.jl
> +  - `etay_nonperiodic`: y-gradient of the non-periodic component of the topographic potential vorticity.
```suggestion
  - `etax_nonperiodic`: ``x``-gradient of the non-periodic component of the topographic potential vorticity.
  - `etay_nonperiodic`: ``y``-gradient of the non-periodic component of the topographic potential vorticity.
```

2022-12-10 10:25 UTC, navidcy commented on src/multilayerqg.jl
> +        etay_nonperiodic = nothing,                   # y-gradient of the non-periodic component of the topographic PV
```suggestion
        etax_nonperiodic = nothing,                   # ``x``-gradient of the non-periodic component of the topographic PV
        etay_nonperiodic = nothing,                   # ``y``-gradient of the non-periodic component of the topographic PV
```

2022-12-10 10:25 UTC, navidcy commented on src/multilayerqg.jl
> +     "array containing periodic component of the topographic PV"
```suggestion
     "array containing the periodic component of the topographic PV"
```

2022-12-18 04:59 UTC, navidcy commented
Sorry for slacking on this. I’m on holiday.

2022-12-18 13:27 UTC, apaloczy commented
No worries at all! Take your time.

2022-12-18 22:40 UTC, navidcy approved these changes

2022-12-18 22:40 UTC, navidcy commented
@apaloczy, I think it's good to go! Have a look at the docstrings additions I made and modify if needed.

2022-12-18 23:27 UTC, navidcy commented
I believe I gave you write rights so you can merge.

2022-12-19 00:25 UTC, navidcy commented
@apaloczy, I'm wondering whether there is a requirement that `etax_nonperiodic` and `etay_nonperiodic` are themselves periodic! I think they should! Otherwise, e.g., the `Qx` term won't be periodic and then errors will be introduced via

https://github.com/apaloczy/GeophysicalFlows.jl/blob/f51365a4587fd483bb7231418e26b3ec6d81bc66/src/multilayerqg.jl#L774-776

right?

2022-12-19 00:26 UTC, navidcy requested changes
let's think more whether the gradients of the non-periodic component of the PV have to be periodic

2022-12-19 03:04 UTC, navidcy commented
Giving this more thought I doubt the non-periodic topo PV would work with anything but constant slope `η = a x + b y`.

2022-12-21 02:00 UTC, glwagner commented
The equations themselves have to be periodic; otherwise the discontinuity at domain "edges" will cause simulations to blow up.

2022-12-21 21:58 UTC, navidcy commented
I had a go at it. Have a look. :)

2022-12-22 11:28 UTC, navidcy approved these changes

2022-12-22 18:44 UTC, apaloczy commented
Sorry for the slowness here. I was offline for a couple of days myself. This all sounds great, I think having the large-scale topographic PV slopes as floats makes sense.

It also makes sense that `Qx` and `Qy` have to be periodic otherwise boundary errors will appear, and a planar slope is the only non-periodic topographic PV possible since it gives a periodic, constant PV gradient.

2022-12-22 18:51 UTC, merged